version: '2'
services:
    qa:
        build: ./quanta/.
        image: barretthugh/QUANTAXIS_docker
        ports:
            - "8080:8080"
            - "3000:3000"
        restart: always

    mgdb:
        image: 3.6.5
        # only for debug, can be disable
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - qamg:/data/db
        restart: always
volumes:
    qamg:
        external:
            name: qamg
