version: '2'
services:
    qa:
        build: ./qa/.
        image: quantaxis:1.0.60
        ports:
            - "8010:8010"
            - "8888:8888"
        environment:
          - MONGODB=mgdb
        restart: always

    mgdb:
        image: mongo:4
        ports:
            - "27017:27017"
        environment:
            - TZ=Asia/Shanghai
            - MONGO_INITDB_DATABASE=quantaxis
        volumes:
            - qamg:/data/db
        restart: always
volumes:
    qamg:
        external:
            name: qamg
